### PR TITLE
feat: generate all /acs routes and resources

### LINKED ISSUE #67: Generate all /acs Seam resources, routes, endpoints, and namespaces
Currently the blueprint only generates routes under `/acs/systems` because that is what is currently documented. We need to generate more of the API surface to ensure the blueprint can handle more complicated resources / parameters, etc. We can try to generate all of `/acs` now without waiting on the full descriptions.

### PR DESCRIPTION
**Pull request by mikewuu**
closes #67

- Added missing `number` param type
- Everything seems to be missing descriptions

### CODE REVIEW

**Comment by mikewuu** [comment]
@razor-x do I need to verify what was generated matches with the API types? Anything in particular to watch out for?

**Comment by razor-x** [comment]
@mikewuu Yes, we need to review the snapshot and make sure it's accurate. If there is anything not handled correctly by the current logic, we need to fix it before we merge this.

**Comment by razor-x** [comment]
Descriptions are blank for now, they need to be added upstream.

**Comment by mikewuu** [comment]
@razor-x does that mean

- resources: verify with type. e.g. https://github.com/seamapi/types/blob/main/src/lib/seam/connect/models/acs/acs-access-group.ts
- endpoints: verify with api route. e.g. https://github.com/seamapi/seam-connect/blob/main/pages/api/public/acs/systems/list.ts

**Comment by razor-x** [comment]
@mikewuu We just want to make sure the output is what we expect and find things we need to address. For example, I'm just noticing that object types are shallow, e.g, this

```
        {
          deprecationMessage: '',
          description: '',
          format: 'record',
          isDeprecated: false,
          isUndocumented: false,
          jsonType: 'object',
          name: 'visionline_metadata',
        }
```

Should keep going with nested `properties`. Made an issue here: https://github.com/seamapi/blueprint/issues/73

Please look though the output and se if you can find anything missing or incorrect, and you can PR to fix them :)

**Review by razor-x — APPROVED** [review]

**Review by razor-x — CHANGES_REQUESTED** [review]
@mikewuu Let's hold off merging this one until the first doc pages are released. In the meantime, take a look at https://github.com/seamapi/blueprint/issues/74 and https://github.com/seamapi/blueprint/issues/73. And you can add the new param type in a separate PR.

Requesting changes for now to avoid early merge.

**Review by andrii-balitskyi — APPROVED** [review]

**Review by razor-x — APPROVED** [review]

**Comment by mikewuu** [comment]
@razor-x is this one now good to merge?

**Comment by razor-x** [comment]
@mikewuu let's merge this and open a new PR on the docs repo to see what happens. Really just want to verify things look ok aside from the missing descriptions.

**Pull request merged**
